@startuml

namespace system.core.libutils.include.utils{

    ' sp
    interface StrongPointer<<h>>
    interface sp<typename T>{
        sp(T* other);
    }
    StrongPointer +-- sp
    interface LightRefBase<<h>>{
        void incStrong(const void* id)
        void decStrong(const void* id
    }
    sp -> LightRefBase

    ' wp
    interface wp{
        wp(T* other);
        wp(const wp<T>& other);
        explicit wp(const sp<T>& other);
        template<typename U> wp(U* other);
        template<typename U> wp(const sp<U>& other);
        template<typename U> wp(const wp<U>& other);
    }
    .RefBase +-- wp
    wp -> RefBase

    interface .RefBase<<h>>{
        weakref_impl* const mRefs;

        weakref_type* createWeak(const void* id) const
        virtual void  onFirstRef()
        inline void incStrong(void* id) const
        inline void decStrong(void* id) const
    }
    class RefBase<<cpp>>
    .RefBase <|.. RefBase

    class weakref_type{
        void incWeak(const void* id)
        void decWeak(const void* id)
    }
    .RefBase +-- weakref_type

    class weakref_impl
    weakref_type <|-- weakref_impl
    RefBase +-- weakref_impl
    .RefBase *-- weakref_impl

    note right of wp::incStrong
    增加强引用计数
    end note
    note right of wp::decStrong
    减少强引用计数
    end note

    note right of .RefBase::incStrong
    增加强引用计数
    end note
    note right of .RefBase::decStrong
    减少强引用计数
    end note
}

@enduml