@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant Activity

ContextImpl ->> SystemServiceRegistry: SystemServiceRegistry.createServiceCache()
SystemServiceRegistry ->> SystemServiceRegistry: static 代码块中 registerService

Activity ->> ContextImpl: getSystemService(CAMERA_SERVICE)
ContextImpl ->> SystemServiceRegistry: getSystemService(this, name)
SystemServiceRegistry ->> ServiceFetcher: getService(ctx)
ServiceFetcher -->> SystemServiceRegistry: return new CameraManager(ctx)
SystemServiceRegistry -->> ContextImpl: return CameraManager
ContextImpl -->> Activity: return CameraManager

@enduml