@startuml
'https://plantuml.com/sequence-diagram

autonumber

rc -> Service: main
Service -> LegacySupport: defaultPassthroughServiceImplementation<ICameraProvider>("legacy/0", 6)
LegacySupport -> CameraProviderAll: getService
LegacySupport -> CameraProviderAll: getService



@enduml